Fix raising exception in flatten api
Fixes:
```
/operatorcourier/flatten.py", line 128, in parse_version_folder
    raise errors.OpCourierBadBundle(msg)
TypeError: __init__() missing 1 required positional argument: 'validation_info'
```

Signed-off-by: Martin Bašti <mbasti@redhat.com>